version: "3.9"

services:
  api:
    build:
      context: ./smelinx-api
      dockerfile: Dockerfile
    env_file:
      - ./smelinx-api/.env
    volumes:
      - ./smelinx-api/data:/app/data        # persist SQLite locally
    ports:
      - "8080:8080"
    restart: unless-stopped

  web:
    build:
      context: ./smelinx-web
      dockerfile: Dockerfile
    env_file:
      - ./smelinx-web/.env
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
